version: '3'

services:
    php:
        container_name: "php-fpm"
        build:
            context: ./php
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ${APP_FOLDER}:/var/www
        user: ${APP_USER}

    nginx:
        container_name: "nginx"
        build:
            context: ./nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        ports:
            - "8181:80"
